# Generated by Django 2.1.1 on 2018-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter sort of link', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='druh',
            field=models.ManyToManyField(help_text='Select druh entered link', to='dang.LinkCaption'),
        ),
    ]
