# Generated by Django 2.1.1 on 2018-12-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0002_auto_20181206_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='druh',
        ),
        migrations.AddField(
            model_name='link',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LinkCaption',
        ),
    ]
