# Generated by Django 2.1.1 on 2018-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0004_auto_20181206_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0),
        ),
    ]
