# Generated by Django 2.1.1 on 2018-12-25 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0006_category_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
